name: Run Root Script

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client and sshpass
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client sshpass

    - name: Run script on server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}  # 从 GitHub Secrets 中读取 SSH 主机名
        SSH_USER: ${{ secrets.SSH_USER }}  # 从 GitHub Secrets 中读取 SSH 用户名
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}  # 从 GitHub Secrets 中读取 SSH 密码
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST '/root/update.sh > /root/update_output.log 2>&1'

        # Capture the exit status of the script
        EXIT_STATUS=$?

        # Fetch the output log from the server
        sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST:/root/update_output.log .

        # Display the output log
        cat update_output.log

        # Output the result of the script
        if [ $EXIT_STATUS -ne 0 ]; then
          echo "Script execution failed with exit status $EXIT_STATUS"
          exit $EXIT_STATUS
        else
          echo "Script executed successfully"
        fi
